module com {
	export module popcap {
		export module flash {
			export module games {
				export module zuma2 {
					export module logic {
						export class Zuma2Sounds extends com.popcap.flash.framework.resources.sounds.BaseSoundManager {
							public static SOUND_CHALLENGE_TIME_UP:string;
							public static SOUND_BALL_COMBO3_CLASS:any;
							public static SOUND_POWERUP_REVERSE1_CLASS:any;
							public static SOUND_POWERUP_REVERSE1:string;
							public static SOUND_CHAIN8_CLASS:any;
							public static SOUND_WARNING1_CLASS:any;
							public static SOUND_CANNON_POWERUP_CLASS:any;
							public static SOUND_BALLS_DESTROYED3_CLASS:any;
							public static SOUND_LEVEL_ZUMA_CLASS:any;
							public static SOUND_SPARKLE_START5_CLASS:any;
							public static SOUND_CANNON_POWERUP:string;
							public static SOUND_BALL_CLICK1_CLASS:any;
							public static SOUND_CHAIN5_CLASS:any;
							public static SOUND_LEVEL_COMPLETE_CLASS:any;
							public static SOUND_BALL_SWAP:string;
							public static SOUND_SPARKLE_START2_CLASS:any;
							public static SOUND_BALL_COMBO5_CLASS:any;
							public static SOUND_POWERUP_SLOWDOWN:string;
							public static SOUND_CHAIN2_CLASS:any;
							public static SOUND_BALL_SWAP_CLASS:any;
							public static SOUND_DEATHSKULL_CHOMP:string;
							public static SOUND_BALLS_ROLLING_CLASS:any;
							public static SOUND_BALLS_DESTROYED5_CLASS:any;
							public static SOUND_BALL_CLICK1:string;
							public static SOUND_BALL_CLICK2:string;
							public static SOUND_FRUIT_APPEARS:string;
							public static SOUND_MAINMENU_BUTTON_OVER_CLASS:any;
							public static SOUND_BALL_COMBO2_CLASS:any;
							public static SOUND_SCORE_COUNTER_CLASS:any;
							public static SOUND_FRUIT_APPEARS_CLASS:any;
							public static SOUND_END_LEVEL_EXPLOSION_CLASS:any;
							public static SOUND_CHAIN7_CLASS:any;
							public static SOUND_SPARKLE_START2:string;
							public static SOUND_SPARKLE_START3:string;
							public static SOUND_SPARKLE_START4:string;
							public static SOUND_LIGHT_TRAIL10:string;
							public static SOUND_SPARKLE_START1:string;
							public static SOUND_LIGHT_TRAIL16:string;
							public static SOUND_LIGHT_TRAIL18:string;
							public static SOUND_EXTRALIFE_CLASS:any;
							public static SOUND_LIGHT_TRAIL13:string;
							public static SOUND_LIGHT_TRAIL14:string;
							public static SOUND_GAPBONUS1:string;
							public static SOUND_LIGHT_TRAIL17:string;
							public static SOUND_SPARKLE_START5:string;
							public static SOUND_LIGHT_TRAIL19:string;
							public static SOUND_LIGHT_TRAIL12:string;
							public static SOUND_BALL_FIRE_CLASS:any;
							public static SOUND_CHAIN1:string;
							public static SOUND_CHAIN2:string;
							public static SOUND_CHAIN3:string;
							public static SOUND_POWERUP_APPEARS2:string;
							public static SOUND_LEVEL_COMPLETE:string;
							public static SOUND_CHAIN6:string;
							public static SOUND_CHAIN8:string;
							public static SOUND_CHAIN9:string;
							public static SOUND_LIGHT_TRAIL15:string;
							public static SOUND_LIGHT_TRAIL20:string;
							public static SOUND_CHAIN7:string;
							public static SOUND_POWERUP_DISAPPEARS_CLASS:any;
							public static SOUND_CHAIN4:string;
							public static SOUND_CHAIN5:string;
							public static SOUND_END_LEVEL_EXPLOSION:string;
							public static SOUND_LIGHT_TRAIL11:string;
							public static SOUND_CHAIN4_CLASS:any;
							public static SOUND_BOMB_EXPLOSION:string;
							public static SOUND_POWERUP_APPEARS2_CLASS:any;
							public static SOUND_BALL_FIRE:string;
							public static SOUND_CHAIN10:string;
							public static SOUND_BALLS_DESTROYED2_CLASS:any;
							public static SOUND_SPARKLE_START4_CLASS:any;
							public static SOUND_CANNON_BLAST_CLASS:any;
							public static SOUND_SPARKLE_START1_CLASS:any;
							public static SOUND_BOMB_EXPLOSION_CLASS:any;
							public static SOUND_BALL_COMBO7_CLASS:any;
							public static SOUND_BALL_COMBO4_CLASS:any;
							public static SOUND_GAPBONUS1_CLASS:any;
							public static SOUND_FRUIT_HIT:string;
							public static SOUND_CHAIN1_CLASS:any;
							public static SOUND_LEVEL_ZUMA:string;
							public static SOUND_CHAIN9_CLASS:any;
							public static SOUND_CANNON_BLAST:string;
							public static SOUND_POWERUP_ACCURACY:string;
							public static SOUND_BUTTON_CLICK:string;
							public static SOUND_BALLS_DESTROYED4_CLASS:any;
							public static SOUND_BALL_COMBO1:string;
							public static SOUND_BALL_COMBO2:string;
							public static SOUND_BALL_COMBO3:string;
							public static SOUND_BALL_COMBO4:string;
							public static SOUND_BALL_COMBO5:string;
							public static SOUND_BALL_COMBO6:string;
							public static SOUND_BALL_COMBO7:string;
							public static SOUND_POWERUP_SLOWDOWN_CLASS:any;
							public static SOUND_BUTTON_CLICK_CLASS:any;
							public static SOUND_WARNING1:string;
							public static SOUND_CHAIN10_CLASS:any;
							public static SOUND_BALLS_DESTROYED1:string;
							public static SOUND_BALLS_DESTROYED3:string;
							public static SOUND_BALLS_DESTROYED4:string;
							public static SOUND_BALLS_DESTROYED5:string;
							public static SOUND_CHALLENGE_TIME_UP_CLASS:any;
							public static SOUND_BALLS_DESTROYED2:string;
							public static SOUND_EXTRALIFE:string;
							public static SOUND_CHAIN6_CLASS:any;
							public static SOUND_BALL_COMBO1_CLASS:any;
							public static SOUND_FRUIT_DISAPPEARS:string;
							public static SOUND_BALLS_DESTROYED1_CLASS:any;
							public static SOUND_FRUIT_HIT_CLASS:any;
							public static SOUND_BALL_CLICK2_CLASS:any;
							public static SOUND_SCORE_COUNTER:string;
							public static SOUND_DEATHSKULL_CHOMP_CLASS:any;
							public static SOUND_POWERUP_ACCURACY_CLASS:any;
							public static SOUND_SPARKLE_START3_CLASS:any;
							public static SOUND_LIGHT_TRAIL1:string;
							public static SOUND_LIGHT_TRAIL3:string;
							public static SOUND_LIGHT_TRAIL4:string;
							public static SOUND_LIGHT_TRAIL5:string;
							public static SOUND_LIGHT_TRAIL6:string;
							public static SOUND_BALLS_ROLLING:string;
							public static SOUND_LIGHT_TRAIL8:string;
							public static SOUND_LIGHT_TRAIL2:string;
							public static SOUND_LIGHT_TRAIL7:string;
							public static SOUND_LIGHT_TRAIL9:string;
							public static SOUND_CHAIN3_CLASS:any;
							public static SOUND_POWERUP_DISAPPEARS:string;
							public static SOUND_GAMEOVER1:string;
							public static SOUND_MAINMENU_BUTTON_OVER:string;
							public static SOUND_BALL_COMBO6_CLASS:any;
							public static SOUND_GAMEOVER1_CLASS:any;
							public static SOUND_FRUIT_DISAPPEARS_CLASS:any;

							public constructor()
							{
								super();
								this.init();
							}

							private init()
							{
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_EXTRALIFE] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_EXTRALIFE_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_END_LEVEL_EXPLOSION] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_END_LEVEL_EXPLOSION_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_POWERUP] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_POWERUP_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_BLAST] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_BLAST_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_ZUMA] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_ZUMA_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_SWAP] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_SWAP_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN2] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN2_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN3] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN3_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN4] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN4_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN5] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN5_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN6] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN6_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN7] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN7_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN8] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN8_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN9] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN9_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN10] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN10_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHALLENGE_TIME_UP] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHALLENGE_TIME_UP_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BUTTON_CLICK] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BUTTON_CLICK_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_MAINMENU_BUTTON_OVER] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_MAINMENU_BUTTON_OVER_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_HIT] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_HIT_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_APPEARS] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_APPEARS_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START2] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START2_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START3] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START3_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START4] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START4_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START5] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START5_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO2] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO2_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO3] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO3_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO4] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO4_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO5] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO5_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO6] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO6_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO7] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO7_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_FIRE] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_FIRE_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK2] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK2_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED2] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED2_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED3] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED3_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED4] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED4_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED5] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED5_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BOMB_EXPLOSION] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BOMB_EXPLOSION_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_DEATHSKULL_CHOMP] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_DEATHSKULL_CHOMP_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_DISAPPEARS] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_DISAPPEARS_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAMEOVER1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAMEOVER1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAPBONUS1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAPBONUS1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_COMPLETE] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_COMPLETE_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_ACCURACY] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_ACCURACY_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_APPEARS2] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_APPEARS2_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_DISAPPEARS] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_DISAPPEARS_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_REVERSE1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_REVERSE1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_SLOWDOWN] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_SLOWDOWN_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SCORE_COUNTER] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SCORE_COUNTER_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_WARNING1] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_WARNING1_CLASS);
								mSounds[com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_ROLLING] = new SoundDescriptor(com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_ROLLING_CLASS);
							}

						}
					}
				}
			}
		}
	}
}

com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHALLENGE_TIME_UP = "SOUND_CHALLENGE_TIME_UP";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO3_CLASS = Zuma2Sounds_SOUND_BALL_COMBO3_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_REVERSE1_CLASS = Zuma2Sounds_SOUND_POWERUP_REVERSE1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_REVERSE1 = "SOUND_POWERUP_REVERSE1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN8_CLASS = Zuma2Sounds_SOUND_CHAIN8_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_WARNING1_CLASS = Zuma2Sounds_SOUND_WARNING1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_POWERUP_CLASS = Zuma2Sounds_SOUND_CANNON_POWERUP_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED3_CLASS = Zuma2Sounds_SOUND_BALLS_DESTROYED3_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_ZUMA_CLASS = Zuma2Sounds_SOUND_LEVEL_ZUMA_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START5_CLASS = Zuma2Sounds_SOUND_SPARKLE_START5_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_POWERUP = "SOUND_CANNON_POWERUP";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK1_CLASS = Zuma2Sounds_SOUND_BALL_CLICK1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN5_CLASS = Zuma2Sounds_SOUND_CHAIN5_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_COMPLETE_CLASS = Zuma2Sounds_SOUND_LEVEL_COMPLETE_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_SWAP = "SOUND_BALL_SWAP";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START2_CLASS = Zuma2Sounds_SOUND_SPARKLE_START2_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO5_CLASS = Zuma2Sounds_SOUND_BALL_COMBO5_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_SLOWDOWN = "SOUND_POWERUP_SLOWDOWN";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN2_CLASS = Zuma2Sounds_SOUND_CHAIN2_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_SWAP_CLASS = Zuma2Sounds_SOUND_BALL_SWAP_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_DEATHSKULL_CHOMP = "SOUND_DEATHSKULL_CHOMP";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_ROLLING_CLASS = Zuma2Sounds_SOUND_BALLS_ROLLING_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED5_CLASS = Zuma2Sounds_SOUND_BALLS_DESTROYED5_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK1 = "SOUND_BALL_CLICK1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK2 = "SOUND_BALL_CLICK2";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_APPEARS = "SOUND_FRUIT_APPEARS";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_MAINMENU_BUTTON_OVER_CLASS = Zuma2Sounds_SOUND_MAINMENU_BUTTON_OVER_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO2_CLASS = Zuma2Sounds_SOUND_BALL_COMBO2_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SCORE_COUNTER_CLASS = Zuma2Sounds_SOUND_SCORE_COUNTER_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_APPEARS_CLASS = Zuma2Sounds_SOUND_FRUIT_APPEARS_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_END_LEVEL_EXPLOSION_CLASS = Zuma2Sounds_SOUND_END_LEVEL_EXPLOSION_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN7_CLASS = Zuma2Sounds_SOUND_CHAIN7_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START2 = "SOUND_SPARKLE_START2";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START3 = "SOUND_SPARKLE_START3";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START4 = "SOUND_SPARKLE_START4";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL10 = "SOUND_LIGHT_TRAIL10";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START1 = "SOUND_SPARKLE_START1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL16 = "SOUND_LIGHT_TRAIL16";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL18 = "SOUND_LIGHT_TRAIL18";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_EXTRALIFE_CLASS = Zuma2Sounds_SOUND_EXTRALIFE_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL13 = "SOUND_LIGHT_TRAIL13";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL14 = "SOUND_LIGHT_TRAIL14";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAPBONUS1 = "SOUND_GAPBONUS1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL17 = "SOUND_LIGHT_TRAIL17";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START5 = "SOUND_SPARKLE_START5";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL19 = "SOUND_LIGHT_TRAIL19";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL12 = "SOUND_LIGHT_TRAIL12";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_FIRE_CLASS = Zuma2Sounds_SOUND_BALL_FIRE_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN1 = "SOUND_CHAIN1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN2 = "SOUND_CHAIN2";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN3 = "SOUND_CHAIN3";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_APPEARS2 = "SOUND_POWERUP_APPEARS2";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_COMPLETE = "SOUND_LEVEL_COMPLETE";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN6 = "SOUND_CHAIN6";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN8 = "SOUND_CHAIN8";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN9 = "SOUND_CHAIN9";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL15 = "SOUND_LIGHT_TRAIL15";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL20 = "SOUND_LIGHT_TRAIL20";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN7 = "SOUND_CHAIN7";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_DISAPPEARS_CLASS = Zuma2Sounds_SOUND_POWERUP_DISAPPEARS_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN4 = "SOUND_CHAIN4";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN5 = "SOUND_CHAIN5";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_END_LEVEL_EXPLOSION = "SOUND_END_LEVEL_EXPLOSION";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL11 = "SOUND_LIGHT_TRAIL11";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN4_CLASS = Zuma2Sounds_SOUND_CHAIN4_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BOMB_EXPLOSION = "SOUND_BOMB_EXPLOSION";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_APPEARS2_CLASS = Zuma2Sounds_SOUND_POWERUP_APPEARS2_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_FIRE = "SOUND_BALL_FIRE";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN10 = "SOUND_CHAIN10";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED2_CLASS = Zuma2Sounds_SOUND_BALLS_DESTROYED2_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START4_CLASS = Zuma2Sounds_SOUND_SPARKLE_START4_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_BLAST_CLASS = Zuma2Sounds_SOUND_CANNON_BLAST_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START1_CLASS = Zuma2Sounds_SOUND_SPARKLE_START1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BOMB_EXPLOSION_CLASS = Zuma2Sounds_SOUND_BOMB_EXPLOSION_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO7_CLASS = Zuma2Sounds_SOUND_BALL_COMBO7_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO4_CLASS = Zuma2Sounds_SOUND_BALL_COMBO4_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAPBONUS1_CLASS = Zuma2Sounds_SOUND_GAPBONUS1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_HIT = "SOUND_FRUIT_HIT";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN1_CLASS = Zuma2Sounds_SOUND_CHAIN1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LEVEL_ZUMA = "SOUND_LEVEL_ZUMA";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN9_CLASS = Zuma2Sounds_SOUND_CHAIN9_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CANNON_BLAST = "SOUND_CANNON_BLAST";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_ACCURACY = "SOUND_POWEUP_ACCURACY";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BUTTON_CLICK = "SOUND_BUTTON_CLICK";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED4_CLASS = Zuma2Sounds_SOUND_BALLS_DESTROYED4_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO1 = "SOUND_BALL_COMBO1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO2 = "SOUND_BALL_COMBO2";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO3 = "SOUND_BALL_COMBO3";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO4 = "SOUND_BALL_COMBO4";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO5 = "SOUND_BALL_COMBO5";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO6 = "SOUND_BALL_COMBO6";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO7 = "SOUND_BALL_COMBO7";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_SLOWDOWN_CLASS = Zuma2Sounds_SOUND_POWERUP_SLOWDOWN_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BUTTON_CLICK_CLASS = Zuma2Sounds_SOUND_BUTTON_CLICK_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_WARNING1 = "SOUND_WARNING1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN10_CLASS = Zuma2Sounds_SOUND_CHAIN10_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED1 = "SOUND_BALLS_DESTROYED1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED3 = "SOUND_BALLS_DESTROYED3";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED4 = "SOUND_BALLS_DESTROYED4";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED5 = "SOUND_BALLS_DESTROYED5";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHALLENGE_TIME_UP_CLASS = Zuma2Sounds_SOUND_CHALLENGE_TIME_UP_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED2 = "SOUND_BALLS_DESTROYED2";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_EXTRALIFE = "SOUND_EXTRALIFE";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN6_CLASS = Zuma2Sounds_SOUND_CHAIN6_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO1_CLASS = Zuma2Sounds_SOUND_BALL_COMBO1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_DISAPPEARS = "SOUND_FRUIT_DISAPPEARS";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_DESTROYED1_CLASS = Zuma2Sounds_SOUND_BALLS_DESTROYED1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_HIT_CLASS = Zuma2Sounds_SOUND_FRUIT_HIT_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_CLICK2_CLASS = Zuma2Sounds_SOUND_BALL_CLICK2_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SCORE_COUNTER = "SOUND_SCORE_COUNTER";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_DEATHSKULL_CHOMP_CLASS = Zuma2Sounds_SOUND_DEATHSKULL_CHOMP_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_ACCURACY_CLASS = Zuma2Sounds_SOUND_POWERUP_ACCURACY_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_SPARKLE_START3_CLASS = Zuma2Sounds_SOUND_SPARKLE_START3_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL1 = "SOUND_LIGHT_TRAIL1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL3 = "SOUND_LIGHT_TRAIL3";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL4 = "SOUND_LIGHT_TRAIL4";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL5 = "SOUND_LIGHT_TRAIL5";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL6 = "SOUND_LIGHT_TRAIL6";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALLS_ROLLING = "SOUND_BALLS_ROLLING";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL8 = "SOUND_LIGHT_TRAIL8";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL2 = "SOUND_LIGHT_TRAIL2";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL7 = "SOUND_LIGHT_TRAIL7";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_LIGHT_TRAIL9 = "SOUND_LIGHT_TRAIL9";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_CHAIN3_CLASS = Zuma2Sounds_SOUND_CHAIN3_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_POWERUP_DISAPPEARS = "SOUND_POWERUP_DISAPPEARS";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAMEOVER1 = "SOUND_GAMEOVER1";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_MAINMENU_BUTTON_OVER = "SOUND_MAINMENU_BUTTON_OVER";
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_BALL_COMBO6_CLASS = Zuma2Sounds_SOUND_BALL_COMBO6_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_GAMEOVER1_CLASS = Zuma2Sounds_SOUND_GAMEOVER1_CLASS;
com.popcap.flash.games.zuma2.logic.Zuma2Sounds.SOUND_FRUIT_DISAPPEARS_CLASS = Zuma2Sounds_SOUND_FRUIT_DISAPPEARS_CLASS;
flash.extendsClass("com.popcap.flash.games.zuma2.logic.Zuma2Sounds","com.popcap.flash.framework.resources.sounds.BaseSoundManager")
